package com.green.dao.output;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.green.dao.output.MyBook;

import com.green.dao.output.MyBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myBookDaoConfig;

    private final MyBookDao myBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myBookDaoConfig = daoConfigMap.get(MyBookDao.class).clone();
        myBookDaoConfig.initIdentityScope(type);

        myBookDao = new MyBookDao(myBookDaoConfig, this);

        registerDao(MyBook.class, myBookDao);
    }
    
    public void clear() {
        myBookDaoConfig.clearIdentityScope();
    }

    public MyBookDao getMyBookDao() {
        return myBookDao;
    }

}
