package com.green.dao.output;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MY_BOOK".
 */
@Entity
public class MyBook {

    @Id
    @Index
    private Long id;
    private String user_id;
    private String title;
    private String cover_url;
    private String content_url;
    private String author;
    private Double read_rate;
    private String formats;
    private Boolean probation;
    private String bookmarks;
    private String notes;
    private String remarks;
    private String folder;
    private Long last_read_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MyBook() {
    }

    public MyBook(Long id) {
        this.id = id;
    }

    @Generated
    public MyBook(Long id, String user_id, String title, String cover_url, String content_url, String author, Double read_rate, String formats, Boolean probation, String bookmarks, String notes, String remarks, String folder, Long last_read_time) {
        this.id = id;
        this.user_id = user_id;
        this.title = title;
        this.cover_url = cover_url;
        this.content_url = content_url;
        this.author = author;
        this.read_rate = read_rate;
        this.formats = formats;
        this.probation = probation;
        this.bookmarks = bookmarks;
        this.notes = notes;
        this.remarks = remarks;
        this.folder = folder;
        this.last_read_time = last_read_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCover_url() {
        return cover_url;
    }

    public void setCover_url(String cover_url) {
        this.cover_url = cover_url;
    }

    public String getContent_url() {
        return content_url;
    }

    public void setContent_url(String content_url) {
        this.content_url = content_url;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Double getRead_rate() {
        return read_rate;
    }

    public void setRead_rate(Double read_rate) {
        this.read_rate = read_rate;
    }

    public String getFormats() {
        return formats;
    }

    public void setFormats(String formats) {
        this.formats = formats;
    }

    public Boolean getProbation() {
        return probation;
    }

    public void setProbation(Boolean probation) {
        this.probation = probation;
    }

    public String getBookmarks() {
        return bookmarks;
    }

    public void setBookmarks(String bookmarks) {
        this.bookmarks = bookmarks;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public Long getLast_read_time() {
        return last_read_time;
    }

    public void setLast_read_time(Long last_read_time) {
        this.last_read_time = last_read_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
