package com.green.dao.output;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {

    @Id
    @Index
    private String id;
    private String name;
    private String url;
    private Integer age;

    // KEEP FIELDS - put your custom fields here
    private boolean hasGrilFriend;
    private int height;
    // KEEP FIELDS END

    @Generated
    public Student() {
    }

    public Student(String id) {
        this.id = id;
    }

    @Generated
    public Student(String id, String name, String url, Integer age) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.age = age;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    // KEEP METHODS - put your custom methods here

    public boolean isHasGrilFriend() {
        return hasGrilFriend;
    }

    public void setHasGrilFriend(boolean hasGrilFriend) {
        this.hasGrilFriend = hasGrilFriend;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    // KEEP METHODS END

}
